@extends('backend.admin.index')
@section('content')
<div class="container">
    <div class="row form-group">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header text-left f-100" style="color:blue;font-weight:700">

                    <div class="row">
                        <div class="col-md-6">
                            Salary Sheets
                        </div>
                       
                        <div class="col-md-6 text-right">
                                @can('generate payroll')
                                <a data-target = "#generate_salary_start" data-toggle = "modal" class="btn btn-primary f-100 text-white">Generate
                                Salary Sheet</a>
                                @endcan
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-sm table-bordered table-striped table-vcenter js-dataTable-full  bg-white">
                        <thead>
                            <tr>
                                <th class="d-none d-sm-table-cell text-center">Year</th>
                                <th class="d-none d-sm-table-cell text-center">Month</th>
                                <th class="d-none d-sm-table-cell text-center">Generation Date</th>
                                <th class="d-none d-sm-table-cell text-center">Generated By</th>
                                <th class="d-none d-sm-table-cell text-center">Grand Total</th>
                                <th class="d-none d-sm-table-cell text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($salary_sheets as $sheet)
                            @php
                              $ff=App\Models\EmployeeSalary::where('salary_generate_id',$sheet->id)->first();
                            @endphp
                            <tr>
                                <td class="text-center">{{ $sheet -> year}}</td>
                                <td class="text-center">{{ $sheet -> month }}</td>
                                <td class="text-center">{{ $sheet -> generate_date }}</td>
                                <td class="text-center">{{ $sheet -> employee -> name }}</td>
                                <td class="text-center">{{ $ff -> net_amount }}</td>
                                <td>
                                    <div class="btn-group">
                                    @can('download payroll')
                                    <a class="btn btn-sm btn-outline-primary" href="{{ route('view-salary-sheet',['generate_id'  => $sheet -> id])}} "><i class="fas fa-eye"></i></a>
                                    <a class="btn btn-sm btn-outline-primary" href="{{ route('download-salary-sheet',['generate_id' => $sheet -> id])}}"><i class="fas fa-download"></i></a>
                                    <a class="btn btn-sm btn-outline-primary" href="{{ route('download-bank-advice',['generate_id' => $sheet -> id])}}"><i class="fas fa-file-download"></i></a>
                                    @endcan
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="modal fade" id="generate_salary_start" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="generate_salary_start">Generate Salary</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action = "{{ route('admin.generate-salary.preview') }}" method = "get">
           @csrf         
          <div class="form-group">
           <label>Year</label>
           <select class = "form-control" name = "year">
             @for($year = 2021; $year <= 2035; $year++)
               <option value = {{ $year }}>{{ $year }}</option>
             @endfor
           </select>
          </div>
          <div class="form-group">
            <label>Month</label>
            <select class = "form-control" name = "month">
            @for($months = 1; $months <= 12; $months++)
             @php $month_name =  date('F', mktime(0, 0, 0, $months, 10));@endphp
              <option value = "{{ $month_name  }}">{{ $month_name }}</option>
            @endfor
           
            </select>
            
          </div>
        
      </div>
      <div class="modal-footer">
        
        <button type="submit" class="btn btn-primary f-100">Procced</button>
      </div>
      </form>
    </div>
  </div>
</div>
@endsection
