@extends('backend.admin.index')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                           <div class="f-roboto">Generated Pension Details</div>
                        </div>
                        <div class="col-md-6 text-right">
                           <a class = "btn btn-primary btn-sm f-100 text-white" href = "{{ route('admin.pension-process.index') }}"><i class = "fa fa-arrow-left mr-2"></i>Back</a>
                        </div>
                    </div>
                    
                </div>
                <div class="card-body">
                        <div class="row mt-2">
                            <div class="col-md-12">
                                <div class="card border-0">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-12 text-right">
                                                 <a class = "btn btn-danger text-white f-100" href = "{{ route('admin.pension-process.download',['id' => $pension_process -> id] ) }}"><i class = "fa fa-print mr-2"></i>Print</a>
                                            </div>
                                        </div>
                                        <div class="row text-center">
                                            <div class="col-md-12">
                                                <h4 class="f-100">Generated pension sheet for the month of {{ $pension_process -> month }} {{ $pension_process -> year }}</h4>
                                            </div>
                                           
                                        </div>
                                       
                                        <div class="row">
                                            <div class="col-md-3 text-right">
                                                <p class = "f-100">Generation Date : </p>
                                            </div>
                                            <div class="col-md-3">
                                                <p class = "f-100">{{ $pension_process -> process_date }}</p>
                                            </div>
                                            <div class="col-md-3 text-right">
                                                <p class = "f-100">Generated By : </p>
                                            </div>
                                            <div class="col-md-3">
                                                <p class = "f-100">{{ $pension_process -> getEmployee -> name  }}</p>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-12">
                                                <table class="table table-sm table-striped table-bordered">
                                                    <thead>
                                                        <tr class="text-center text-black">
                                                            <th>Employee</th>
                                                            <th>Grade</th>
                                                            <th>PayScale</th>
                                                            <th>Last Basic Pay</th>
                                                            <th>Basic Pension</th>
                                                            <th>Health Allow.</th>
                                                            <th>
                                                                Bonus
                                                            </th>
                                                            <th>Total</th>
                                                            <th>Status</th>
                                                        </tr>

                                                    </thead>
                                                    <tbody>
                                                        @php $details = $pension_process -> processDetails; @endphp

                                                        @foreach($details as $detail)
                                                          @php $user = $detail -> getPensionUser; @endphp
                                                        <tr class="text-center">
                                                            <td>{{ $user -> getEmployee -> name }}</td>
                                                            <td>{{ $user -> getGrade -> name  }}</td>
                                                            <td>{{ $user -> getPayScale -> name  }}</td>
                                                            <td>{{ $user -> last_basic_pay }}</td>
                                                            <td>{{ $user -> basic_pension_amount }}</td>
                                                            <td>{{ $user -> health_fee }}</td>
                                                            <td>
                                                                {{ $detail -> bonus }}
                                                            </td>
                                                            <td>{{ $pension_process -> total_amount }}</td>
                                                            <td>
                                                                @if($detail -> status == 1)
                                                                  Paid
                                                                @else
                                                                 <button type = "button" class ="btn btn-primary btn-sm f-100" onclick = "mark_as_paid(this,'{{ $detail -> id }}')">Done</button>
                                                                @endif 
                                                            </td>
                                                        </tr>
                                                        @endforeach
                                                        <tr class = "text-center">
                                                           <td colspan = "4">
                                                               Total
                                                           </td>
                                                           <td>{{ $details -> sum('basic_pension_amount') }}</td>
                                                           <td>{{ $details -> sum('health_fee') }}</td>
                                                           <td>{{ $details -> sum('bonus') }}</td>
                                                           <td>{{ $details -> sum('total_amount') }}</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script>
    function mark_as_paid(ref,detail_id)
    {
       $(ref).html('<i class = "fa fa-spinner fa-spin"></i>');
       $.ajaxSetup({
           headers:
           {
               'X-CSRF-Token' : "{{ csrf_token() }}"
           }
       });
       $.ajax({
           url : "{{ route('admin.pension.mark-as-paid') }}",
           type : "post",
           data : { detail_id : detail_id }
       }).done(function(){
           $(ref).html('Paid');
           $(ref).attr('disabled',true);
       })
    }
</script>
@endpush
