<!DOCTYPE html>
<html>

<head>
    <title>Pension Sheet</title>
    <style type="text/css">
    @page {
        size: 8.5in 11in;
    }

    .body {
        font-family: "verdana", Arial, Georgia;
    }

    .container {
        width: 100%;
        padding-top: 5px;
    }

    .table {
        width: 100%;
        border-collapse: collapse;
    }

    .table thead tr th,
    .table tbody tr td {
        padding: 2px;
        text-align: center;
        font-size: 10pt;
        padding-top:10px;
        border:1px solid black;
    }


    .footer {
        padding-top: 70px;
        width: 100%;
    }

    .footer tr td {
        text-align: right;
        width: 25%;
        font-size: 10pt;
        font-weight: bold;
    }

    .heading h3 {
        text-align: center;
        text-decoration: none;
        margin-bottom: 5px;

    }

    .heading p {
        text-align: center;
        margin-top: 0;
        padding-top: 0;
    }

    p {
        font-size: 10pt;
    }
    </style>
</head>

<body>
    
    <div class="container">
        <h3 style = "text-align:center">{{ $company -> company_name  }}</h3>
        <h4 style = "text-align:center;line-height:5px">Pension sheet for the month of {{ $pension_process -> month }} {{ $pension_process -> year }}</h4>

        <table class = "table" style = "border:none;margin-bottom:10px;">
          <thead>
              <tr style = "border:none">
                  <th style = "border:none">Generation Date : </th>
                  <th style = "border:none">{{ $pension_process -> process_date }}</th>
                  <th style = "border:none">Generated By : </th>
                  <th style = "border:none">{{ $pension_process -> getEmployee -> name  }}</th>
              </tr>
          </thead>
        </table>
        
        <table class="table">
            <thead>
                <tr>
                    <th>Employee</th>
                    <th>Grade</th>
                    <th>PayScale</th>
                    <th>Last Basic Pay</th>
                    <th>Basic Pension</th>
                    <th>Health Allowance</th>
                    <th>Bonus</th>
                    <th>Total</th>
                </tr>
                
            </thead>
            @php $details =$pension_process -> processDetails; @endphp
            <tbody>
               @foreach($details as $detail)
                 @php $user = $detail -> getPensionUser; @endphp
                <tr style = "text-align:center">
                   <td>
                       {{ $user -> getEmployee -> name }}
                   </td>
                   <td>{{ $user -> getGrade -> name  }}</td>
                   <td>{{ $user -> getPayScale -> name  }}</td>
                   <td style = "text-align:right">{{ $user -> last_basic_pay }}</td>
                   <td style = "text-align:right">{{ $user -> basic_pension_amount }}</td>
                   <td style = "text-align:right">{{ $user -> health_fee }}</td>
                   <td style = "text-align:right">{{ $detail -> bonus }}</td>
                   <td style = "text-align:right">{{ $pension_process -> total_amount }}</td>
                </tr>
                @endforeach
                <tr>
                    <td colspan = "4" style = "text-align:right">
                         Total
                    </td>
                    <td style = "text-align:right">{{ $details -> sum('basic_pension_amount') }}</td>
                    <td style = "text-align:right">{{ $details -> sum('health_fee') }}</td>
                    <td style = "text-align:right">{{ $details -> sum('bonus') }}</td>
                    <td style = "text-align:right">{{ $details -> sum('total_amount') }}</td>
                </tr>
                <tr>
                    <td colspan = "8" style = "text-align:center;text-transform:uppercase;font-weight:700;font-size:14px;">
                        InWords : {{ $Inwords }}
                    </td>
                    
                </tr>
            </tbody>
        </table>
    </div>
</body>

</html>